---
- name: download setup script
  get_url:
    dest: /usr/local/bin/setup_{{ node_js_version }}
    mode: u+x
    url: http://deb.nodesource.com/setup_{{ node_js_version }}

- name: execute setup script
  shell: setup_{{ node_js_version }} > /var/log/setup_{{ node_js_version }}.log
  args:
    creates: /var/log/setup_{{ node_js_version }}.log

- name: install dependencies
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - nodejs
    - build-essential
